---
- name: Set root password
  hosts: hosts_to_apply
  tasks:
  - name: Generate random password
    set_fact:
      password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=15') }}"
    when: password is not defined
    changed_when: password is defined
    notify: 
      - Show password

  - name: Install python dependencies
    pip:
      name: passlib
    delegate_to: localhost

  - name: Generate password hash
    shell: |
      from passlib.hash import sha512_crypt
      pass_clear_txt = "{{ password }}"
      pass_hash = sha512_crypt.encrypt(pass_clear_txt)
      print(pass_hash)
    register: python_out
    args:
      executable: /usr/bin/python
    delegate_to: localhost

  - name: Set password
    user:
      name: root
      update_password: always
      password: "{{ python_out.stdout }}"

  handlers:
  - name: Show password
    debug:
      msg: "Take note: {{ password }}"
        